version: '3.7'
services:
  pg:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ../../db/pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    environment:
      - ADMINER_DEFAULT_SERVER=pg
    depends_on:
      - pg
